# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Composer build + rsync drupal site

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
#     - uses: actions/checkout@v3
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v3
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#     - run: npm ci
#     - run: npm run build --if-present
#     - name: Composer Action
#   # You may pin to the exact commit or the version.
#   # uses: MilesChou/composer-action@9988f07d80864ce70f00d17430809ba931d9bc84
#       uses: MilesChou/composer-action@v1.0.2
#       with:
#         args: install
#     - name: composer-php
      # You may pin to the exact commit or the version.
      # uses: nick-zh/composer@7d8fabe9f01d0d721a55e712b5fa83d35d584df1
#     - uses: nick-zh/composer@php7.4
    - name: Composer install
#       working-directory: ./
      run: cd ../../../../ | composer install
      #     - name: PHP Composer
#   # You may pin to the exact commit or the version.
#   # uses: baschny/php-composer-action@93b5aef92179c5ebba8824db8d34748301c6a70e
#       uses: baschny/php-composer-action@v1
#       with:
#         # What version of Composer to use
#         composer_version: 2
#         # Composer command to run (or get_config to just get the output vars)
#         command: install
        # Command line arguments to composer
        # OAuth token for accessing github private resources
#         github_oauth: # optional, default is 
    # You may pin to the exact commit or the version.
    # uses: shimataro/ssh-key-action@685d0f20da72e4b53cc81d373a2ed0a867770e46
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2.5.1
      with:
#       SSH private key
        key: ${{ secrets.NHT_DEPLOY_KEY }}
#         SSH key file name (default: id_rsa)
#         public keys of SSH servers
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
#         SSH config
    - name: Adding Known Hosts
      run: ssh-keyscan -H  ${{ secrets.NHT_DEPLOY_HOST_IP }}  >> ~/.ssh/known_hosts  
#     # Rsync deploy
    - name: Deploy Composer dependencies with rsync
      run: "rsync -avz vendor/ ${{ secrets.NHT_DEPLOY_USER }}@${{ secrets.NHT_DEPLOY_HOST_IP }}:/home4/rtkmelmy/vendor"
    - name: Deploy Drupal config sync files with rsync
      run: "rsync -avz config/ ${{ secrets.NHT_DEPLOY_USER }}@${{ secrets.NHT_DEPLOY_HOST_IP }}:/home4/rtkmelmy/config"
    - name: Deploy Drupal files with rsync
      run: "rsync -avz web/ --exclude-paths=files;working:js:css:php:styles:tmp:priv:google_tag:webform:documents ${{ secrets.NHT_DEPLOY_USER }}@${{ secrets.NHT_DEPLOY_HOST_IP }}:/home4/rtkmelmy/public_html"
